kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx2048M
kotlin.native.ignoreDisabledTargets=true

org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true

android.nonTransitiveRClass=true
android.useAndroidX=true

# Only use the runtime provisioned via Gradle. Locally installed jdks (ie Android Studio's bundled JBR) don't have jmods, needed by
# the desktop release build for ProGuard and jpackage.
org.gradle.java.installations.auto-detect=false
