[versions]
kotlin = "2.4.20"
kotlinx-coroutines = "1.11.0"
kotlin-serialization = "1.11.0"
agp = "9.4.1"
koin = "4.2.2"
log4j = "2.26.1"
slf4j = "2.0.19"

#noinspection UnusedVersionCatalogEntry
android-compileSdk = "37"
#noinspection UnusedVersionCatalogEntry
android-minSdk = "26"
#noinspection UnusedVersionCatalogEntry
android-targetSdk = "37"
#noinspection UnusedVersionCatalogEntry
jvm-toolchain = "21"

compose = "1.12.0"
compose-material = "1.9.0"
compose-materialIconsExtended = "1.7.3"
compose-navigation = "2.9.2"
compose-navigation-event = "1.1.0"
compose-stability-analyzer = "0.14.0"

androidx-activityCompose = "1.13.0"
androidx-core = "1.19.0"
androidx-datastore = "1.2.1"
jetbrains-lifecycle = "2.11.0"

androidx-camera = "1.6.2"
guava = "33.7.1-android"
webcam-capture = "0.3.12"
javacpp = "1.5.14"
ffmpeg = "8.1.2-1.5.14"

cryptography = "0.6.0"
qrose = "1.3.0"
zxing = "3.5.4"

ktor = "3.6.0"
jmdns = "3.6.3"
oshi = "7.0.0"

ktlint-gradle = "14.2.0"
#noinspection UnusedVersionCatalogEntry
ktlint = "1.8.0"
detekt = "1.23.8"

junit = "6.1.3"

[libraries]
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
compose-material = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-material" }
compose-material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "compose-materialIconsExtended" }
compose-navigation = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "compose-navigation" }
compose-navigation-event = { group = "org.jetbrains.androidx.navigationevent", name = "navigationevent-compose", version.ref = "compose-navigation-event" }
compose-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose" }

jetbrains-lifecycle-common = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-common", version.ref = "jetbrains-lifecycle" }
jetbrains-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "jetbrains-lifecycle" }
jetbrains-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "jetbrains-lifecycle" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "androidx-core" }
androidx-datastore = { module = "androidx.datastore:datastore-preferences-core", version.ref = "androidx-datastore" }

# Camera libraries
androidx-camera-compose = { group = "androidx.camera", name = "camera-compose", version.ref = "androidx-camera" }
androidx-camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "androidx-camera" }
androidx-camera-impl = { group = "androidx.camera", name = "camera-camera2", version.ref = "androidx-camera" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "androidx-camera" }
androidx-camera-video = { group = "androidx.camera", name = "camera-video", version.ref = "androidx-camera" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
webcam-capture = { group = "com.github.sarxos", name = "webcam-capture", version.ref = "webcam-capture" }
javacpp = { group = "org.bytedeco", name = "javacpp", version.ref = "javacpp" }
ffmpeg = { group = "org.bytedeco", name = "ffmpeg", version.ref = "ffmpeg" }

kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-jvm = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlin-serialization" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidxCompose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-composeViewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }

cryptography-core = { module = "dev.whyoleg.cryptography:cryptography-core", version.ref = "cryptography" }
cryptography-provider-jdk = { module = "dev.whyoleg.cryptography:cryptography-provider-jdk", version.ref = "cryptography" }
qrose = { module = "io.github.alexzhirkevich:qrose", version.ref = "qrose" }
zxing = { module = "com.google.zxing:core", version.ref = "zxing" }
zxing-jvm = { module = "com.google.zxing:javase", version.ref = "zxing" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor" }
ktor-server-logging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor" }
ktor-websockets = { module = "io.ktor:ktor-websockets", version.ref = "ktor" }
ktor-network-tls-certificates = { module = "io.ktor:ktor-network-tls-certificates", version.ref = "ktor" }
jmdns = { module = "org.jmdns:jmdns", version.ref = "jmdns" }
oshi = { module = "com.github.oshi:oshi-core-java11", version.ref = "oshi" }

log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

junit-platform = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-stability-analyzer = { id = "com.github.skydoves.compose.stability.analyzer", version.ref = "compose-stability-analyzer" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-gradle" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

[bundles]
ktor-client = [
    "ktor-client-core",
    "ktor-client-cio",
    "ktor-client-websockets",
    "ktor-client-logging",
]
ktor-server = [
    "ktor-server-core",
    "ktor-server-websockets",
    "ktor-server-logging",
]
