build:
  maxIssues: 0

complexity:
  LongMethod:
    threshold: 80
    ignoreAnnotated:
      - "Composable"
  LongParameterList:
    functionThreshold: 8
    constructorThreshold: 10
    excludes: ['**ViewModel.kt']
    ignoreAnnotated:
      - "Composable"
  CyclomaticComplexMethod:
    threshold: 20
  TooManyFunctions:
    thresholdInFiles: 20
    thresholdInClasses: 20
    thresholdInInterfaces: 15
    thresholdInObjects: 15
    thresholdInEnums: 10

naming:
  FunctionNaming:
    ignoreAnnotated:
      - "Composable"
  TopLevelPropertyNaming:
    constantPattern: "[A-Z][A-Za-z0-9_]*"
  MatchingDeclarationName:
    multiplatformTargets: [ 'android', 'common', 'jvm', 'desktop' ]

potential-bugs:
  # detekt 1.23 has false positives on early returns, ignore for now.
  UnreachableCode:
    active: false

style:
  MagicNumber:
    active: false
  MaxLineLength:
    maxLineLength: 140
  WildcardImport:
    active: true
    excludeImports:
      - "kotlinx.coroutines.flow.*"
  UnusedPrivateMember:
    allowedNames: "(_.*|TAG)"
    ignoreAnnotated: [ 'Preview' ]
  ReturnCount:
    active: false

# detekt 1.23 has plenty of false positives on suspend modifiers and dispatcher injection, ignore for now.
coroutines:
  RedundantSuspendModifier:
    active: false
  InjectDispatcher:
    active: false
